# Generated by Django 3.2.11 on 2022-02-02 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_autentic', '0001_initial'),
    ]

    operations = [
    ]

def create_data(apps,schema_editor):
    app_autentic = apps.get_model('app_autentic', 'App_autentic')
    app_autentic(first_name='AAA', last_name='BBB', email='CCC@gmail.com',senha='DDDD')

class Migrations(migrations.Migration):
    dependencies = [
        ('app_autenic', '0001_initial'),
    ]
    operations = [
        migrations.RunPython(create_data),
    ]