# Generated by Django 4.0.1 on 2022-02-02 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Videos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('video', models.FileField(upload_to='')),
                ('destaque', models.CharField(choices=[('DS', 'Destaque_S'), ('DN', 'Destaque_N')], default='DN', max_length=10)),
            ],
        ),
    ]
