# Generated by Django 4.0.1 on 2022-02-03 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_videos', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Videos',
            new_name='Video',
        ),
    ]
