# Generated by Django 4.0.1 on 2022-02-04 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_videos', '0009_alter_video_video'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='video',
        ),
    ]
