# Generated by Django 4.0.1 on 2022-02-04 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_videos', '0010_remove_video_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='video',
            field=models.FileField(blank=True, upload_to='video/%y'),
        ),
        migrations.AlterField(
            model_name='video',
            name='destaque',
            field=models.CharField(choices=[('sim', 'sim'), ('nao', 'nao')], default='nao', max_length=10),
        ),
    ]
