# Generated by Django 4.0.1 on 2022-02-07 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_videos', '0012_alter_video_video'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='video',
            new_name='file',
        ),
    ]
