# Generated by Django 4.0.2 on 2022-02-07 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nome', models.CharField(max_length=100)),
                ('Sobrenome', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('usuario', models.CharField(max_length=100)),
                ('senha', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'Usuario',
            },
        ),
    ]
