# Generated by Django 4.0.2 on 2022-02-08 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auntt', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='email',
        ),
    ]
